// swift-tools-version: 6.0
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription

let package = Package(
    name: "RiimGameCore",
    platforms: [
        .iOS(.v14)
    ],
    products: [
        // Products define the executables and libraries a package produces, making them visible to other packages.
        .library(
            name: "RiimGameCore",
            targets: ["RiimGameCore", "RiimGBASwift"]),
    ],
    dependencies: [
        .package(url: "https://github.com/weichsel/ZIPFoundation.git", from: "0.9.11"),
    ],
    targets: [
        // Targets are the basic building blocks of a package, defining a module or a test suite.
        // Targets can depend on other targets in this package and products from dependencies.
        .target(
            name: "RiimGameCore"
        ),
        .target(
            name: "RiimGBAGameBridge",
            dependencies: ["RiimGameCore"],
            path: "Sources/RiimGBAGameBridge",
            exclude: [
                "../RiimGBAGame/mGBA/CHANGES",
                "../RiimGBAGame/mGBA/cinema",
                "../RiimGBAGame/mGBA/CMakeLists.txt",
                "../RiimGBAGame/mGBA/CONTRIBUTING.md",
                "../RiimGBAGame/mGBA/doc/mgba-qt.6",
                "../RiimGBAGame/mGBA/doc/mgba.6",
                "../RiimGBAGame/mGBA/include",
                "../RiimGBAGame/mGBA/LICENSE",
                "../RiimGBAGame/mGBA/opt",
                "../RiimGBAGame/mGBA/PORTING.md",
                "../RiimGBAGame/mGBA/README_DE.md",
                "../RiimGBAGame/mGBA/README_ES.md",
                "../RiimGBAGame/mGBA/README_ZH_CN.md",
                "../RiimGBAGame/mGBA/README.md",
                "../RiimGBAGame/mGBA/res",
                "../RiimGBAGame/mGBA/src/arm/CMakeLists.txt",
                "../RiimGBAGame/mGBA/src/arm/debugger",
                "../RiimGBAGame/mGBA/src/core/CMakeLists.txt",
                "../RiimGBAGame/mGBA/src/core/flags.h.in",
                "../RiimGBAGame/mGBA/src/core/scripting.c",
                "../RiimGBAGame/mGBA/src/core/test",
                "../RiimGBAGame/mGBA/src/core/version.c.in",
                "../RiimGBAGame/mGBA/src/debugger",
                "../RiimGBAGame/mGBA/src/feature",
                "../RiimGBAGame/mGBA/src/gb/CMakeLists.txt",
                "../RiimGBAGame/mGBA/src/gb/debugger/cli.c",
                "../RiimGBAGame/mGBA/src/gb/debugger/debugger.c",
                "../RiimGBAGame/mGBA/src/gb/debugger/symbols.c",
                "../RiimGBAGame/mGBA/src/gb/extra/proxy.c",
                "../RiimGBAGame/mGBA/src/gb/test",
                "../RiimGBAGame/mGBA/src/gba/CMakeLists.txt",
                "../RiimGBAGame/mGBA/src/gba/debugger/cli.c",
                "../RiimGBAGame/mGBA/src/gba/extra/audio-mixer.c",
                "../RiimGBAGame/mGBA/src/gba/extra/battlechip.c",
                "../RiimGBAGame/mGBA/src/gba/extra/proxy.c",
                "../RiimGBAGame/mGBA/src/gba/hle-bios.make",
                "../RiimGBAGame/mGBA/src/gba/hle-bios.s",
                "../RiimGBAGame/mGBA/src/gba/renderers/gl.c",
                "../RiimGBAGame/mGBA/src/gba/sharkport.c",
                "../RiimGBAGame/mGBA/src/gba/sio/dolphin.c",
                "../RiimGBAGame/mGBA/src/gba/sio/joybus.c",
                "../RiimGBAGame/mGBA/src/gba/test",
                "../RiimGBAGame/mGBA/src/platform/3ds",
                "../RiimGBAGame/mGBA/src/platform/cmake",
                "../RiimGBAGame/mGBA/src/platform/example",
                "../RiimGBAGame/mGBA/src/platform/libretro",
                "../RiimGBAGame/mGBA/src/platform/openemu",
                "../RiimGBAGame/mGBA/src/platform/opengl",
                "../RiimGBAGame/mGBA/src/platform/psp2",
                "../RiimGBAGame/mGBA/src/platform/python",
                "../RiimGBAGame/mGBA/src/platform/qt",
                "../RiimGBAGame/mGBA/src/platform/sdl",
                "../RiimGBAGame/mGBA/src/platform/switch",
                "../RiimGBAGame/mGBA/src/platform/test",
                "../RiimGBAGame/mGBA/src/platform/wii",
                "../RiimGBAGame/mGBA/src/platform/windows",
                "../RiimGBAGame/mGBA/src/third-party/blip_buf/license.txt",
                "../RiimGBAGame/mGBA/src/third-party/discord-rpc",
                "../RiimGBAGame/mGBA/src/third-party/inih/LICENSE.txt",
                "../RiimGBAGame/mGBA/src/third-party/inih/README.md",
                "../RiimGBAGame/mGBA/src/third-party/libpng",
                "../RiimGBAGame/mGBA/src/third-party/lzma",
                "../RiimGBAGame/mGBA/src/third-party/sqlite3",
                "../RiimGBAGame/mGBA/src/third-party/zlib",
                "../RiimGBAGame/mGBA/src/util/CMakeLists.txt",
                "../RiimGBAGame/mGBA/src/util/convolve.c",
                "../RiimGBAGame/mGBA/src/util/elf-read.c",
                "../RiimGBAGame/mGBA/src/util/gui.c",
                "../RiimGBAGame/mGBA/src/util/gui/file-select.c",
                "../RiimGBAGame/mGBA/src/util/gui/font-metrics.c",
                "../RiimGBAGame/mGBA/src/util/gui/font.c",
                "../RiimGBAGame/mGBA/src/util/gui/menu.c",
                "../RiimGBAGame/mGBA/src/util/memory.c",
                "../RiimGBAGame/mGBA/src/util/ring-fifo.c",
                "../RiimGBAGame/mGBA/src/util/test",
                "../RiimGBAGame/mGBA/src/util/vfs/vfs-devlist.c",
                "../RiimGBAGame/mGBA/src/util/vfs/vfs-file.c",
                "../RiimGBAGame/mGBA/src/util/vfs/vfs-lzma.c",
                "../RiimGBAGame/mGBA/src/util/vfs/vfs-zip.c",
                "../RiimGBAGame/mGBA/tools",
                "../RiimGBAGame/mGBA/version.cmake",
            ],
            sources: [
                "../RiimGBAGame/mGBA/src/arm/arm.c",
                "../RiimGBAGame/mGBA/src/arm/decoder-arm.c",
                "../RiimGBAGame/mGBA/src/arm/decoder-thumb.c",
                "../RiimGBAGame/mGBA/src/arm/decoder.c",
                "../RiimGBAGame/mGBA/src/arm/isa-arm.c",
                "../RiimGBAGame/mGBA/src/arm/isa-thumb.c",
                "../RiimGBAGame/mGBA/src/core/bitmap-cache.c",
                "../RiimGBAGame/mGBA/src/core/cache-set.c",
                "../RiimGBAGame/mGBA/src/core/cheats.c",
                "../RiimGBAGame/mGBA/src/core/core.c",
                "../RiimGBAGame/mGBA/src/core/config.c",
                "../RiimGBAGame/mGBA/src/core/directories.c",
                "../RiimGBAGame/mGBA/src/core/input.c",
                "../RiimGBAGame/mGBA/src/core/interface.c",
                "../RiimGBAGame/mGBA/src/core/library.c",
                "../RiimGBAGame/mGBA/src/core/lockstep.c",
                "../RiimGBAGame/mGBA/src/core/log.c",
                "../RiimGBAGame/mGBA/src/core/map-cache.c",
                "../RiimGBAGame/mGBA/src/core/mem-search.c",
                "../RiimGBAGame/mGBA/src/core/rewind.c",
                "../RiimGBAGame/mGBA/src/core/serialize.c",
                "../RiimGBAGame/mGBA/src/core/sync.c",
                "../RiimGBAGame/mGBA/src/core/thread.c",
                "../RiimGBAGame/mGBA/src/core/tile-cache.c",
                "../RiimGBAGame/mGBA/src/core/timing.c",
                "../RiimGBAGame/mGBA/src/gb/cheats.c",
                "../RiimGBAGame/mGBA/src/gb/core.c",
                "../RiimGBAGame/mGBA/src/gb/gb.c",
                "../RiimGBAGame/mGBA/src/gb/input.c",
                "../RiimGBAGame/mGBA/src/gb/io.c",
                "../RiimGBAGame/mGBA/src/gb/mbc.c",
                "../RiimGBAGame/mGBA/src/gb/mbc",
                "../RiimGBAGame/mGBA/src/sm83/sm83.c",
                "../RiimGBAGame/mGBA/src/sm83/isa-sm83.c",
                "../RiimGBAGame/mGBA/src/gb/memory.c",
                "../RiimGBAGame/mGBA/src/gb/overrides.c",
                "../RiimGBAGame/mGBA/src/gb/renderers/cache-set.c",
                "../RiimGBAGame/mGBA/src/gb/renderers/software.c",
                "../RiimGBAGame/mGBA/src/gb/serialize.c",
                "../RiimGBAGame/mGBA/src/gb/sio.c",
                "../RiimGBAGame/mGBA/src/gb/sio/lockstep.c",
                "../RiimGBAGame/mGBA/src/gb/sio/printer.c",
                "../RiimGBAGame/mGBA/src/gb/timer.c",
                "../RiimGBAGame/mGBA/src/gb/video.c",
                "../RiimGBAGame/mGBA/src/gb/audio.c",
                "../RiimGBAGame/mGBA/src/gba/audio.c",
                "../RiimGBAGame/mGBA/src/gba/bios.c",
                "../RiimGBAGame/mGBA/src/gba/cart/ereader.c",
                "../RiimGBAGame/mGBA/src/gba/cart/gpio.c",
                "../RiimGBAGame/mGBA/src/gba/cart/matrix.c",
                "../RiimGBAGame/mGBA/src/gba/cart/vfame.c",
                "../RiimGBAGame/mGBA/src/gba/cheats.c",
                "../RiimGBAGame/mGBA/src/gba/cheats/codebreaker.c",
                "../RiimGBAGame/mGBA/src/gba/cheats/gameshark.c",
                "../RiimGBAGame/mGBA/src/gba/cheats/parv3.c",
                "../RiimGBAGame/mGBA/src/gba/core.c",
                "../RiimGBAGame/mGBA/src/gba/dma.c",
                "../RiimGBAGame/mGBA/src/gba/gba.c",
                "../RiimGBAGame/mGBA/src/gba/hle-bios.c",
                "../RiimGBAGame/mGBA/src/gba/input.c",
                "../RiimGBAGame/mGBA/src/gba/io.c",
                "../RiimGBAGame/mGBA/src/gba/memory.c",
                "../RiimGBAGame/mGBA/src/gba/overrides.c",
                "../RiimGBAGame/mGBA/src/gba/renderers/cache-set.c",
                "../RiimGBAGame/mGBA/src/gba/renderers/common.c",
                "../RiimGBAGame/mGBA/src/gba/renderers/software-bg.c",
                "../RiimGBAGame/mGBA/src/gba/renderers/software-mode0.c",
                "../RiimGBAGame/mGBA/src/gba/renderers/software-obj.c",
                "../RiimGBAGame/mGBA/src/gba/renderers/video-software.c",
                "../RiimGBAGame/mGBA/src/gba/savedata.c",
                "../RiimGBAGame/mGBA/src/gba/serialize.c",
                "../RiimGBAGame/mGBA/src/gba/sio.c",
                "../RiimGBAGame/mGBA/src/gba/sio/gbp.c",
                "../RiimGBAGame/mGBA/src/gba/sio/lockstep.c",
                "../RiimGBAGame/mGBA/src/gba/timer.c",
                "../RiimGBAGame/mGBA/src/gba/video.c",
                "../RiimGBAGame/mGBA/src/platform/posix/memory.c",
                "../RiimGBAGame/mGBA/src/third-party/blip_buf/blip_buf.c",
                "../RiimGBAGame/mGBA/src/third-party/inih/ini.c",
                "../RiimGBAGame/mGBA/src/util/circle-buffer.c",
                "../RiimGBAGame/mGBA/src/util/configuration.c",
                "../RiimGBAGame/mGBA/src/util/crc32.c",
                "../RiimGBAGame/mGBA/src/util/formatting.c",
                "../RiimGBAGame/mGBA/src/util/gbk-table.c",
                "../RiimGBAGame/mGBA/src/util/hash.c",
                "../RiimGBAGame/mGBA/src/util/patch-fast.c",
                "../RiimGBAGame/mGBA/src/util/patch-ips.c",
                "../RiimGBAGame/mGBA/src/util/patch-ups.c",
                "../RiimGBAGame/mGBA/src/util/patch.c",
                "../RiimGBAGame/mGBA/src/util/string.c",
                "../RiimGBAGame/mGBA/src/util/table.c",
                "../RiimGBAGame/mGBA/src/util/text-codec.c",
                "../RiimGBAGame/mGBA/src/util/vector.c",
                "../RiimGBAGame/mGBA/src/util/vfs.c",
                "../RiimGBAGame/mGBA/src/util/vfs/vfs-dirent.c",
                "../RiimGBAGame/mGBA/src/util/vfs/vfs-fd.c",
                "../RiimGBAGame/mGBA/src/util/vfs/vfs-fifo.c",
                "../RiimGBAGame/mGBA/src/util/vfs/vfs-mem.c"
            ],
            publicHeadersPath: "",
            cSettings: [
                .headerSearchPath(""),
                .headerSearchPath("../RiimGBAGame/mGBA"),
                .headerSearchPath("../RiimGBAGame/mGBA/src"),
                .headerSearchPath("../RiimGBAGame/mGBA/include"),
                
                .define("DM_CORE_GBA"),
                .define("DDISABLE_THREADING"),
                .define("DMINIMAL_CORE", to: "1"),
                .define("DMGBA_STANDALONE"),
                .define("DHAVE_STRDUP"),
                .define("DHAVE_XLOCALE"),
                .define("DHAVE_STRNDUP"),
                .define("DHAVE_STRLCPY"),
                .define("DHAVE_LOCALTIME_R"),
                .define("DHAVE_LOCALE"),
                .define("DHAVE_STRTOF_L"),
                .define("DHAVE_SNPRINTF_L"),
                .define("DHAVE_SETLOCALE"),
                
                .define("M_CORE_GBA"),
                .define("DISABLE_THREADING"),
                .define("MINIMAL_CORE", to: "1"),
                .define("MGBA_STANDALONE"),
                .define("HAVE_STRDUP"),
                .define("HAVE_XLOCALE"),
                .define("HAVE_STRNDUP"),
                .define("HAVE_STRLCPY"),
                .define("HAVE_LOCALTIME_R"),
                .define("HAVE_LOCALE"),
                .define("HAVE_STRTOF_L"),
                .define("HAVE_SNPRINTF_L"),
                .define("HAVE_SETLOCALE"),
            ]
        ),
        .target(
            name: "RiimGBASwift",
            dependencies: ["RiimGBAGameBridge", "RiimGameCore"],
            path: "Sources/RiimGBASwift",
            cSettings: [
                .headerSearchPath("../RiimGBAGame/"),
                .headerSearchPath("../RiimGBAGame/mGBA"),
                .headerSearchPath("../RiimGBAGame/mGBA/src"),
                .headerSearchPath("../RiimGBAGame/mGBA/include"),
                
                .define("DM_CORE_GBA"),
                .define("DDISABLE_THREADING"),
                .define("DMINIMAL_CORE", to: "1"),
                .define("DMGBA_STANDALONE"),
                .define("DHAVE_STRDUP"),
                .define("DHAVE_XLOCALE"),
                .define("DHAVE_STRNDUP"),
                .define("DHAVE_STRLCPY"),
                .define("DHAVE_LOCALTIME_R"),
                .define("DHAVE_LOCALE"),
                .define("DHAVE_STRTOF_L"),
                .define("DHAVE_SNPRINTF_L"),
                .define("DHAVE_SETLOCALE"),
                
                .define("M_CORE_GBA"),
                .define("DISABLE_THREADING"),
                .define("MINIMAL_CORE", to: "1"),
                .define("MGBA_STANDALONE"),
                .define("HAVE_STRDUP"),
                .define("HAVE_XLOCALE"),
                .define("HAVE_STRNDUP"),
                .define("HAVE_STRLCPY"),
                .define("HAVE_LOCALTIME_R"),
                .define("HAVE_LOCALE"),
                .define("HAVE_STRTOF_L"),
                .define("HAVE_SNPRINTF_L"),
                .define("HAVE_SETLOCALE"),
            ]
        ),
        .testTarget(
            name: "RiimGameCoreTests",
            dependencies: ["RiimGameCore"]
        ),
    ]
)
