// swift-tools-version: 6.0
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription

let package = Package(
    name: "RiimGameCore",
    platforms: [
        .iOS(.v14)
    ],
    products: [
        // Products define the executables and libraries a package produces, making them visible to other packages.
        .library(
            name: "RiimGameCore",
            targets: ["RiimGameCore", "RiimGBASwift"]),
    ],
    dependencies: [
        .package(url: "https://github.com/weichsel/ZIPFoundation.git", from: "0.9.11"),
    ],
    targets: [
        // Targets are the basic building blocks of a package, defining a module or a test suite.
        // Targets can depend on other targets in this package and products from dependencies.
        .target(
            name: "RiimGameCore"
        ),
        .target(
            name: "RiimGBASwift",
            dependencies: ["RiimGBAGameBridge", "RiimGameCore"],
            path: "Sources/RiimGBASwift",
            publicHeadersPath: "",
            cSettings: [
//                .headerSearchPath("../"),
//                .headerSearchPath("../RiimGBAGame"),
//                .headerSearchPath("../RiimGBAGame/src"),
//                .headerSearchPath("../RiimGBAGame/include"),
                
                .define("DM_CORE_GBA"),
                .define("DDISABLE_THREADING"),
                .define("DMINIMAL_CORE", to: "1"),
                .define("DMGBA_STANDALONE"),
                .define("DHAVE_STRDUP"),
                .define("DHAVE_XLOCALE"),
                .define("DHAVE_STRNDUP"),
                .define("DHAVE_STRLCPY"),
                .define("DHAVE_LOCALTIME_R"),
                .define("DHAVE_LOCALE"),
                .define("DHAVE_STRTOF_L"),
                .define("DHAVE_SNPRINTF_L"),
                .define("DHAVE_SETLOCALE"),
                
                .define("M_CORE_GBA"),
                .define("DISABLE_THREADING"),
                .define("MINIMAL_CORE", to: "1"),
                .define("MGBA_STANDALONE"),
                .define("HAVE_STRDUP"),
                .define("HAVE_XLOCALE"),
                .define("HAVE_STRNDUP"),
                .define("HAVE_STRLCPY"),
                .define("HAVE_LOCALTIME_R"),
                .define("HAVE_LOCALE"),
                .define("HAVE_STRTOF_L"),
                .define("HAVE_SNPRINTF_L"),
                .define("HAVE_SETLOCALE"),
            ]
        ),
        .target(
            name: "RiimGBAGameBridge",
            dependencies: ["RiimGameCore"],
            path: "Sources/RiimGBAGameBridge",
            publicHeadersPath: "",
            cSettings: [
                .headerSearchPath("../"),
                .headerSearchPath("../RiimGBAGame"),
                .headerSearchPath("../RiimGBAGame/src"),
                .headerSearchPath("../RiimGBAGame/include"),
                
                .define("DM_CORE_GBA"),
                .define("DDISABLE_THREADING"),
                .define("DMINIMAL_CORE", to: "1"),
                .define("DMGBA_STANDALONE"),
                .define("DHAVE_STRDUP"),
                .define("DHAVE_XLOCALE"),
                .define("DHAVE_STRNDUP"),
                .define("DHAVE_STRLCPY"),
                .define("DHAVE_LOCALTIME_R"),
                .define("DHAVE_LOCALE"),
                .define("DHAVE_STRTOF_L"),
                .define("DHAVE_SNPRINTF_L"),
                .define("DHAVE_SETLOCALE"),
                
                .define("M_CORE_GBA"),
                .define("DISABLE_THREADING"),
                .define("MINIMAL_CORE", to: "1"),
                .define("MGBA_STANDALONE"),
                .define("HAVE_STRDUP"),
                .define("HAVE_XLOCALE"),
                .define("HAVE_STRNDUP"),
                .define("HAVE_STRLCPY"),
                .define("HAVE_LOCALTIME_R"),
                .define("HAVE_LOCALE"),
                .define("HAVE_STRTOF_L"),
                .define("HAVE_SNPRINTF_L"),
                .define("HAVE_SETLOCALE"),
            ]
        ),
//        .target(
//            name: "RiimGBAGame",
//            path: "Sources/RiimGBAGame",
//            exclude: [
//                "CHANGES",
//                "cinema",
//                "CMakeLists.txt",
//                "CONTRIBUTING.md",
//                "doc/mgba-qt.6",
//                "doc/mgba.6",
//                "include",
//                "LICENSE",
//                "opt",
//                "PORTING.md",
//                "README_DE.md",
//                "README_ES.md",
//                "README_ZH_CN.md",
//                "README.md",
//                "res",
//                "src/arm/CMakeLists.txt",
//                "src/arm/debugger",
//                "src/core/CMakeLists.txt",
//                "src/core/flags.h.in",
//                "src/core/scripting.c",
//                "src/core/test",
//                "src/core/version.c.in",
//                "src/debugger",
//                "src/feature",
//                "src/gb/CMakeLists.txt",
//                "src/gb/debugger/cli.c",
//                "src/gb/debugger/debugger.c",
//                "src/gb/debugger/symbols.c",
//                "src/gb/extra/proxy.c",
//                "src/gb/test",
//                "src/gba/CMakeLists.txt",
//                "src/gba/debugger/cli.c",
//                "src/gba/extra/audio-mixer.c",
//                "src/gba/extra/battlechip.c",
//                "src/gba/extra/proxy.c",
//                "src/gba/hle-bios.make",
//                "src/gba/hle-bios.s",
//                "src/gba/renderers/gl.c",
//                "src/gba/sharkport.c",
//                "src/gba/sio/dolphin.c",
//                "src/gba/sio/joybus.c",
//                "src/gba/test",
//                "src/platform/3ds",
//                "src/platform/cmake",
//                "src/platform/example",
//                "src/platform/libretro",
//                "src/platform/openemu",
//                "src/platform/opengl",
//                "src/platform/psp2",
//                "src/platform/python",
//                "src/platform/qt",
//                "src/platform/sdl",
//                "src/platform/switch",
//                "src/platform/test",
//                "src/platform/wii",
//                "src/platform/windows",
//                "src/third-party/blip_buf/license.txt",
//                "src/third-party/discord-rpc",
//                "src/third-party/inih/LICENSE.txt",
//                "src/third-party/inih/README.md",
//                "src/third-party/libpng",
//                "src/third-party/lzma",
//                "src/third-party/sqlite3",
//                "src/third-party/zlib",
//                "src/util/CMakeLists.txt",
//                "src/util/convolve.c",
//                "src/util/elf-read.c",
//                "src/util/gui.c",
//                "src/util/gui/file-select.c",
//                "src/util/gui/font-metrics.c",
//                "src/util/gui/font.c",
//                "src/util/gui/menu.c",
//                "src/util/memory.c",
//                "src/util/ring-fifo.c",
//                "src/util/test",
//                "src/util/vfs/vfs-devlist.c",
//                "src/util/vfs/vfs-file.c",
//                "src/util/vfs/vfs-lzma.c",
//                "src/util/vfs/vfs-zip.c",
//                "tools",
//                "version.cmake",
//            ], sources: [
//                "src/arm/arm.c",
//                "src/arm/decoder-arm.c",
//                "src/arm/decoder-thumb.c",
//                "src/arm/decoder.c",
//                "src/arm/isa-arm.c",
//                "src/arm/isa-thumb.c",
//                "src/core/bitmap-cache.c",
//                "src/core/cache-set.c",
//                "src/core/cheats.c",
//                "src/core/core.c",
//                "src/core/config.c",
//                "src/core/directories.c",
//                "src/core/input.c",
//                "src/core/interface.c",
//                "src/core/library.c",
//                "src/core/lockstep.c",
//                "src/core/log.c",
//                "src/core/map-cache.c",
//                "src/core/mem-search.c",
//                "src/core/rewind.c",
//                "src/core/serialize.c",
//                "src/core/sync.c",
//                "src/core/thread.c",
//                "src/core/tile-cache.c",
//                "src/core/timing.c",
//                "src/gb/cheats.c",
//                "src/gb/core.c",
//                "src/gb/gb.c",
//                "src/gb/input.c",
//                "src/gb/io.c",
//                "src/gb/mbc.c",
//                "src/gb/mbc",
//                "src/sm83/sm83.c",
//                "src/sm83/isa-sm83.c",
//                "src/gb/memory.c",
//                "src/gb/overrides.c",
//                "src/gb/renderers/cache-set.c",
//                "src/gb/renderers/software.c",
//                "src/gb/serialize.c",
//                "src/gb/sio.c",
//                "src/gb/sio/lockstep.c",
//                "src/gb/sio/printer.c",
//                "src/gb/timer.c",
//                "src/gb/video.c",
//                "src/gb/audio.c",
//                "src/gba/audio.c",
//                "src/gba/bios.c",
//                "src/gba/cart/ereader.c",
//                "src/gba/cart/gpio.c",
//                "src/gba/cart/matrix.c",
//                "src/gba/cart/vfame.c",
//                "src/gba/cheats.c",
//                "src/gba/cheats/codebreaker.c",
//                "src/gba/cheats/gameshark.c",
//                "src/gba/cheats/parv3.c",
//                "src/gba/core.c",
//                "src/gba/dma.c",
//                "src/gba/gba.c",
//                "src/gba/hle-bios.c",
//                "src/gba/input.c",
//                "src/gba/io.c",
//                "src/gba/memory.c",
//                "src/gba/overrides.c",
//                "src/gba/renderers/cache-set.c",
//                "src/gba/renderers/common.c",
//                "src/gba/renderers/software-bg.c",
//                "src/gba/renderers/software-mode0.c",
//                "src/gba/renderers/software-obj.c",
//                "src/gba/renderers/video-software.c",
//                "src/gba/savedata.c",
//                "src/gba/serialize.c",
//                "src/gba/sio.c",
//                "src/gba/sio/gbp.c",
//                "src/gba/sio/lockstep.c",
//                "src/gba/timer.c",
//                "src/gba/video.c",
//                "src/platform/posix/memory.c",
//                "src/third-party/blip_buf/blip_buf.c",
//                "src/third-party/inih/ini.c",
//                "src/util/circle-buffer.c",
//                "src/util/configuration.c",
//                "src/util/crc32.c",
//                "src/util/formatting.c",
//                "src/util/gbk-table.c",
//                "src/util/hash.c",
//                "src/util/patch-fast.c",
//                "src/util/patch-ips.c",
//                "src/util/patch-ups.c",
//                "src/util/patch.c",
//                "src/util/string.c",
//                "src/util/table.c",
//                "src/util/text-codec.c",
//                "src/util/vector.c",
//                "src/util/vfs.c",
//                "src/util/vfs/vfs-dirent.c",
//                "src/util/vfs/vfs-fd.c",
//                "src/util/vfs/vfs-fifo.c",
//                "src/util/vfs/vfs-mem.c"
//            ],
//            publicHeadersPath: "include",
//            cSettings: [
//                .headerSearchPath(""),
//                .headerSearchPath("src"),
//                .headerSearchPath("include"),
//                
//                .define("DM_CORE_GBA"),
//                .define("DDISABLE_THREADING"),
//                .define("DMINIMAL_CORE", to: "1"),
//                .define("DMGBA_STANDALONE"),
//                .define("DHAVE_STRDUP"),
//                .define("DHAVE_XLOCALE"),
//                .define("DHAVE_STRNDUP"),
//                .define("DHAVE_STRLCPY"),
//                .define("DHAVE_LOCALTIME_R"),
//                .define("DHAVE_LOCALE"),
//                .define("DHAVE_STRTOF_L"),
//                .define("DHAVE_SNPRINTF_L"),
//                .define("DHAVE_SETLOCALE"),
//                
//                .define("M_CORE_GBA"),
//                .define("DISABLE_THREADING"),
//                .define("MINIMAL_CORE", to: "1"),
//                .define("MGBA_STANDALONE"),
//                .define("HAVE_STRDUP"),
//                .define("HAVE_XLOCALE"),
//                .define("HAVE_STRNDUP"),
//                .define("HAVE_STRLCPY"),
//                .define("HAVE_LOCALTIME_R"),
//                .define("HAVE_LOCALE"),
//                .define("HAVE_STRTOF_L"),
//                .define("HAVE_SNPRINTF_L"),
//                .define("HAVE_SETLOCALE"),
//            ]
//        ),
        .testTarget(
            name: "RiimGameCoreTests",
            dependencies: ["RiimGameCore"]
        ),
    ]
)
